language: python
dist: xenial

python:
  - 2.7
  - 3.6
  - 3.7
  - pypy3

env:
  matrix:
    - IMPACTLAB_TOOLS_TEST_ENV=conda
    - IMPACTLAB_TOOLS_TEST_ENV=tox

matrix:
  exclude:
    - python: pypy3
      env: IMPACTLAB_TOOLS_TEST_ENV=conda

install:
  - if [[ "$IMPACTLAB_TOOLS_TEST_ENV" == "conda" ]]; then
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        fi;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda config --add channels conda-forge;
      conda config --set channel_priority strict;
      conda update -q conda;
      conda info -a;
      conda create -q -n impactlab_tools python=$TRAVIS_PYTHON_VERSION;
      source activate impactlab_tools;
      conda install --yes --file requirements_conda.txt;
      python -m pip install -r requirements.txt;
      python -m pip install -r requirements_test.txt;
    else
      python -m pip install tox-travis;
    fi

script:
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - if [[ "$IMPACTLAB_TOOLS_TEST_ENV" == "conda" ]]; then
      source activate impactlab_tools;
      python -m pytest && sphinx-build -W -b html -d docs/_build/doctrees docs/. docs/_build/html;
    else
      tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypy\(py\)\?\([0-9\.\-]\+\)\?/pypy/');
    fi

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: PdilUlbMb4TMiqDlk2d9/GxS+xZC8EOsRPperQFXIAifCBbMdzQJQkJzmyRVdC44ncIf3Fwb8dJvNYTUAzhIFdbmNPvTop+9lTiGP96RHa9X6dDLpoAQaowqPwex0pGILnRUt65TKrOYkIiXUjisKomsI7QeFoeaCsN7t28N+vdHnGHLVhAvSininfOboDB6/6prd/MNjZp8iV3boAC7Wt6q1KAwdV1E0OHh1TO7wsn5Mz+hvnDEWi7TS9KB5v3GProvI3zFl32wNrQ6Xhm4rxfaPrk1hDZk9lzDx+YMWqpt2yNAXpfakn6GVoixBkkiGvZCKt7aEFj4b+9d4dIsUKGE0RbyqSDXUeMNzJouIgnj3DGRcz8HnVr0IS5xe+6aRE+t3W0poPAzryi6JnU41uxLygw9wkT6PRUTGimEo+qTvbGtWz2TIv1N4IX5Lx4abnwGwpOMnH47JaUmG9DZCA3k6UEY2k7JDuNYff7Vt8IIs46FLzjyEW3DjlodSOqrDlHzpmjlxJdScT/ae/JQjjf6L7bS3yFii5tYPeZ/mjWNRPRVkFzRXUpEd7P6gyX8xYuk2puYWDrs42xm93rMZ/WenJF76Nh2CEg/J2s9P3fL70LyOl4Y1q3MN3pRCMAghG+dZRUH8WttluoSfxp9OffiAqQ4AkTLNbwjtOsXDCM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ClimateImpactLab/impactlab-tools

services:
  - docker

before_install:
  - docker pull tray/dynamodb-local

notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - coveralls
