name: Python package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow}}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  codequality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Format check with ruff
        run: |
          ruff check .
        
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install package
        run: |
          pip install . --no-deps
      - name: Test with pytest
        run: |
          pytest -v --cov-report term-missing --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        
